#!/bin/bash
rm *.ar*
rm *.orig

./ArithmeticEncoder c zel.txt zel.ar-$1 $1
./ArithmeticEncoder c war war.ar-$1 $1
./ArithmeticEncoder c libpulse.so libpulse.ar-$1 $1
./ArithmeticEncoder c libgs.so libgs.ar-$1 $1
./ArithmeticEncoder c qt.dll qt.ar-$1 $1
./ArithmeticEncoder c empty empty.ar-$1 $1
./ArithmeticEncoder c idiot.txt idiot.ar-$1 $1
./ArithmeticEncoder c 100a 100a.ar-$1 $1

ls -l *$1*
ls -l *$1* | awk '{ print $5 }' | awk 'BEGIN { rsum = 0 } { rsum += $1 } END { print rsum }'
 
./ArithmeticEncoder d zel.ar-$1 zel.orig
./ArithmeticEncoder d libgs.ar-$1 gs.orig
./ArithmeticEncoder d libpulse.ar-$1 libpulse.orig
./ArithmeticEncoder d war.ar-$1 war.orig
./ArithmeticEncoder d qt.ar-$1 qt.orig
./ArithmeticEncoder d empty.ar-$1 empty.orig
./ArithmeticEncoder d idiot.ar-$1 idiot.orig
./ArithmeticEncoder d 100a.ar-$1 100a.orig

cmp zel.txt zel.orig
cmp libgs.so gs.orig
cmp libpulse.orig libpulse.so
cmp war.orig war
cmp qt.dll qt.orig
cmp empty empty.orig
cmp idiot.txt idiot.orig
cmp 100a 100a.orig
