#!/bin/bash
cd /home/vlad/programming/build-ArithmeticEncoder-Desktop-Release/
make
cp ArithmeticEncoder /home/vlad/arithmetic
cd /home/vlad/arithmetic
./ArithmeticEncoder c zel.txt zel.ar-$1 $1
./ArithmeticEncoder c war war.ar-$1 $1
./ArithmeticEncoder c libpulse.so libpulse.ar-$1 $1
./ArithmeticEncoder c libgs.so libgs.ar-$1 $1

ls -l *$1*
ls -l *$1* | awk '{ print $5 }' | awk 'BEGIN { rsum = 0 } { rsum += $1 } END { print rsum }'
 
./ArithmeticEncoder d zel.ar-$1 zel.orig $1
cmp zel.txt zel.orig

./ArithmeticEncoder d libgs.ar-$1 gs.orig $1
cmp libgs.so gs.orig

./ArithmeticEncoder d libpulse.ar-$1 libpulse.orig $1
cmp libpulse.orig libpulse.so

./ArithmeticEncoder d war.ar-$1 war.orig $1
cmp war.orig war
